config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      redirect_to @todo_list, notice: 'Successfully content created'
    end
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.destroy
    redirect_to @todo_list, notice: 'Successfully content destroyed'
  end

  def complete
    @todo_item.completed_at=  Time.now
    @todo_item.save
    redirect_to @todo_list, notice: "Todo item completed"
  end

  private
  def todo_item_params
    params.require(:todo_item).permit(:content)
  end

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :find_todo_list, only: [:show, :edit, :update, :show, :destroy]
  def index
    @todo_lists = TodoList.all.order('created_at DESC')
  end

  def new
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
    if @todo_list.save
      redirect_to @todo_list, notice: 'Successfully created'
    else
      render :new  
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to @todo_list, notice: 'Successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @todo_list.destroy
    redirect_to root_path, notice: 'Successfully destroy'
  end

  private
  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end

  def find_todo_list
    @todo_list = TodoList.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.3.1/css/all.css", :integrity => "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU", :rel => "stylesheet"}/
  %body
    = render 'layouts/shared/messages'
    = yield

app/views/layouts/shared/_messages.html.haml
-flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/todo_items/_form.html.haml
= form_for [@todo_list,TodoItem.new] do |f|
  %p
    = f.label :content
    = f.text_field :content
  %p= f.submit

app/views/todo_items/_todo_item.html.haml
- if todo_item.completed?
  .complete
    = link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do
      %i.fa.fa-check{:style => "opacity: 0.4;"}
  .todo_item
    %p{:style => "opacity: 0.4;"}
      %strike= todo_item.content
  .trash
    = link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do
      %i.fa.fa-trash
- else
  .complete
    = link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do
      %i.fa.fa-check
  .todo_item
    %p= todo_item.content
  .trash
    = link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do
      %i.fa.fa-trash

app/views/todo_lists/_form.html.haml
= form_for @todo_list do |f|
  -if @todo_list.errors.any?
    %h2= pluralize(@todo_list.errors.count, 'error')
    %ul
      -@todo_list.errors.full_messages.each do |msg|
        %li= msg

  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.text_area :description
  %p
    = f.submit

app/views/todo_lists/edit.html.haml
= render 'form'

app/views/todo_lists/index.html.haml
- @todo_lists.each do |todo_list|
  %p= link_to todo_list.title, todo_list
%p= link_to 'New', new_todo_list_path

app/views/todo_lists/new.html.haml
= render 'form'

app/views/todo_lists/show.html.haml
= @todo_list.title
= link_to 'edit', edit_todo_list_path(@todo_list)
= link_to 'delete', todo_list_path(@todo_list), method: :delete
%p content:
= render @todo_list.todo_items
= render 'todo_items/form'